import sys
import os
from environs import Env

env = Env()
env.read_env()

os.environ['ENV_PATH'] = os.path.dirname(os.path.abspath(__file__))
DEBUG = env.bool('DEBUG', default=False)

THRIFTCLIENT_TRANSPORT = env.str('THRIFTCLIENT_TRANSPORT')
THRIFTCLIENT_PROTOCOL = env.str('THRIFTCLIENT_PROTOCOL')
THRIFTCLIENT_BUFFERED = env.bool('THRIFTCLIENT_BUFFERED')
THRIFTCLIENT_ZLIB = env.bool('THRIFTCLIENT_ZLIB')
THRIFTCLIENT_FRAMED = env.bool('THRIFTCLIENT_FRAMED')

THRIFTSERVER_TRANSPORT = env.str('THRIFTSERVER_TRANSPORT')
THRIFTSERVER_PROTOCOL = env.str('THRIFTSERVER_PROTOCOL')
THRIFTSERVER_BUFFERED = env.bool('THRIFTSERVER_BUFFERED')
THRIFTSERVER_ZLIB = env.bool('THRIFTSERVER_ZLIB')
THRIFTSERVER_FRAMED = env.bool('THRIFTSERVER_FRAMED')

QUEUES = env.str('QUEUES')

